// <auto-generated />
using System;
using MaliyetDataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaliyetDataAccess.Migrations
{
    [DbContext(typeof(TenderContext))]
    partial class TenderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MaliyetEntities.Concrete.TenderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TenderTypes");
                });

            modelBuilder.Entity("MaliyetEntities.Concrete.Unit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MaliyetEntities.Tender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnalysisRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Contratprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EnthusiastFoundation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTypeWorkLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KirimRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketResearchRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpproximateCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpproximateCostAfterTender")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OtherExplanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherFoundationContractPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoseRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PreviousCPTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousConractPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousOCTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousOpproximateCoast")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceDifference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TenderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenderRegisterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TendererProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderingProcedure")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("MaliyetEntities.Tender", b =>
                {
                    b.HasOne("MaliyetEntities.Concrete.TenderType", null)
                        .WithMany("Tenders")
                        .HasForeignKey("TenderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaliyetEntities.Concrete.Unit", null)
                        .WithMany("Tenders")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaliyetEntities.Concrete.TenderType", b =>
                {
                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("MaliyetEntities.Concrete.Unit", b =>
                {
                    b.Navigation("Tenders");
                });
#pragma warning restore 612, 618
        }
    }
}
